### PR TITLE
Add important README content

### PR DESCRIPTION
**Pull request by smably**

### CODE REVIEW

**Review by KevinRizzoTO — APPROVED** [review]
🎉

**Review by aodanx — APPROVED** [review]

**Review by KevinRizzoTO — APPROVED** [review]
N I C E

**Review by KevinRizzoTO — APPROVED** [review]
# 🔥 🚒

**Review by KevinRizzoTO — APPROVED** [review]
🥇

**Review by KevinRizzoTO — APPROVED** [review]
💯

**Review by KevinRizzoTO — APPROVED** [review]
👍

**Review by KevinRizzoTO — APPROVED** [review]
:shipit: 🐏

**Review by KevinRizzoTO — APPROVED** [review]
LGTM

**Review by KevinRizzoTO — APPROVED** [review]
YAAAAS

**Review by KevinRizzoTO — APPROVED** [review]

**Pull request closed without merging**
